name = "openfile-visits"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "openfile-visits"
database_id = "2ce81ce2-6896-4a38-b110-c822865e51b8"
